site_name: Tomahna Project Wiki
nav: 
  - 'Project': '/project/index.md'
  - 'Exile': '/myst3/index.md'
  - 'Revelation': '/myst4/index.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode    
      primary: cyan
      accent: teal
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
      primary: cyan
      accent: teal

#extra:
#  social:
#    - icon: fontawesome/brands/github-alt
#      link: https://github.com/james-willett
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/TheJamesWillett
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/tomahnaproject"  target="_blank" rel="noopener">Tomahna Project</a> - 
  If you need to edit this wiki, please go to the <a href="https://github.com/TomahnaProject/tomahna-project-wiki"  target="_blank" rel="noopener">tomahna-project-wiki</a> repository.