site_name: Tomahna Project Wiki
site_url: "https://tomahnaproject.github.io/tomahna-project-wiki"
repo_url: "https://github.com/TomahnaProject/tomahna-project-wiki"
repo_name: TomahnaProject/tomahna-project-wiki
copyright: |
  &copy; 2024 <a href="https://github.com/tomahnaproject"  target="_blank" rel="noopener">Tomahna Project</a> - 
  If you wish to edit this wiki, please go to the <a href="https://github.com/TomahnaProject/tomahna-project-wiki"  target="_blank" rel="noopener">tomahna-project-wiki</a> repository.

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode    
      primary: cyan
      accent: teal
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
      primary: cyan
      accent: teal

#extra:
#  social:
#    - icon: fontawesome/brands/github-alt
#      link: https://github.com/james-willett
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/TheJamesWillett
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/willettjames/

strict: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized
